/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.Igra;
import model.Potez;
import model.ModelTabelePotez;
import model.WrapIgraPotezi;
import transfer.KlijentZahtev;
import transfer.Operacije;
import transfer.ServerOdg;

/**
 *
 * @author USER
 */
public class KlijentForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentForma
     */
     private Timer t1, t2, t3, t4;
    private int brpok=0;
    private int prethmes, prethrb=1, prethnije;
    private String prethkomb;
    private List<Potez>potezi;
    private model.ModelTabelePotez m;
    public KlijentForma() {
        initComponents();
        t1 = new Timer(300, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                postaviBroj(jLabel1);
            }
        });
        t2 = new Timer(300, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                postaviBroj(jLabel2);
            }
        });
        t3 = new Timer(300, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                postaviBroj(jLabel3);
            }
        });
        t4 = new Timer(300, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                postaviBroj(jLabel4);
            }
        });
        potezi=new LinkedList<>();
        m=new ModelTabelePotez(new LinkedList<>());
        jTable1.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_start1 = new javax.swing.JButton();
        jButton_start2 = new javax.swing.JButton();
        jButton_start3 = new javax.swing.JButton();
        jButton_start4 = new javax.swing.JButton();
        jButton_stop1 = new javax.swing.JButton();
        jButton_stop2 = new javax.swing.JButton();
        jButton_stop3 = new javax.swing.JButton();
        jButton_stop4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_nije = new javax.swing.JLabel();
        jLabel_namestu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 80, 72, 57));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("3");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 72, 57));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 80, 72, 57));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 80, 72, 57));

        jButton_start1.setText("start-1");
        jButton_start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_start1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_start1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 39, -1, -1));

        jButton_start2.setText("start-2");
        jButton_start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_start2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_start2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 39, -1, -1));

        jButton_start3.setText("start-3");
        jButton_start3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_start3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_start3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 39, -1, -1));

        jButton_start4.setText("start-4");
        jButton_start4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_start4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_start4, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 39, -1, -1));

        jButton_stop1.setText("stop-1");
        jButton_stop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_stop1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_stop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jButton_stop2.setText("stop-2");
        jButton_stop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_stop2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_stop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jButton_stop3.setText("stop-3");
        jButton_stop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_stop3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_stop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jButton_stop4.setText("stop-4");
        jButton_stop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_stop4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_stop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jButton1.setText("POSALIJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel5.setText("Broj pogodjenih cifara koje NISU na svom mestu:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel6.setText("Broj pogodjenih cifara koje JESU na svom mestu:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RB", "Kombinacija", "Pogodjenih NA MESTU ", "Pogodjenih NISU NA MESTU "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 600, 160));

        jLabel_nije.setText("0");
        getContentPane().add(jLabel_nije, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 30, -1));

        jLabel_namestu.setText("0");
        getContentPane().add(jLabel_namestu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_start2ActionPerformed
        t2.start();
    }//GEN-LAST:event_jButton_start2ActionPerformed

    private void jButton_stop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_stop2ActionPerformed
        t2.stop();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_stop2ActionPerformed

    private void jButton_stop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_stop1ActionPerformed
        t1.stop();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_stop1ActionPerformed

    private void jButton_start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_start1ActionPerformed
        t1.start();
    }//GEN-LAST:event_jButton_start1ActionPerformed

    private void jButton_start3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_start3ActionPerformed
        t3.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_start3ActionPerformed

    private void jButton_start4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_start4ActionPerformed
        t4.start();
    }//GEN-LAST:event_jButton_start4ActionPerformed

    private void jButton_stop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_stop3ActionPerformed
        t3.stop();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_stop3ActionPerformed

    private void jButton_stop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_stop4ActionPerformed
        t4.stop();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_stop4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (t1.isRunning() || t2.isRunning() || t3.isRunning() || t4.isRunning()) {
            JOptionPane.showMessageDialog(this, "prvo odaberi brojeve");
            return;
        }
        brpok++;
        int[] pog = new int[]{Integer.valueOf(jLabel1.getText()), Integer.valueOf(jLabel2.getText()), Integer.valueOf(jLabel3.getText()), Integer.valueOf(jLabel4.getText())};
        komunikacija.Komunikacija.getInstance().posaljiZahtev(new KlijentZahtev(pog, Operacije.POGADJA));
        ServerOdg so=komunikacija.Komunikacija.getInstance().procitajOdgovor();
        int []stat=(int[]) so.getOdg();
        int namestu=stat[0];
        int nije=stat[1];
        jLabel_namestu.setText(namestu+"");
        jLabel_nije.setText(nije+"");
//        PODESAVNJE TABELE
        podesi_tabelu(namestu,nije);
//        
        if(namestu==4)
        {
            JOptionPane.showMessageDialog(this, "pobeda");
            jButton1.setEnabled(false);
            Igra i=new Igra(-1, new Date(), null, "pobedio", brpok);
            komunikacija.Komunikacija.getInstance().posaljiZahtev(new KlijentZahtev(new WrapIgraPotezi(i, potezi), Operacije.GOTOVA_IGRA));
            return ;
        }
        if(brpok==6){
            JOptionPane.showMessageDialog(this, "soriska izgubio si");
            jButton1.setEnabled(false);
            Igra i=new Igra(-1, new Date(), null, "izgubio", brpok);
            komunikacija.Komunikacija.getInstance().posaljiZahtev(new KlijentZahtev(new WrapIgraPotezi(i, potezi), Operacije.GOTOVA_IGRA));
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    private void postaviBroj(JLabel labela) {
//        int i = 0;
//        double f = Math.random() / Math.nextDown(1.0);
//        double x = 0 * (1.0 - f) + 6 * f;
//        i = (int) x;
//        labela.setText(i + "");
          if(Integer.valueOf(labela.getText())==5)
          {
              labela.setText("0");
              return ;
          }
          labela.setText(Integer.valueOf(labela.getText())+1+"");
    }
    public void podesi_tabelu(int namestu, int nije) {
        potezi.add(new Potez(null,brpok, namestu, nije, String.join("-", new String[]{jLabel1.getText(),jLabel2.getText(),jLabel3.getText(),jLabel4.getText()})));
         m.getPotezi().clear();
        for(int i=0;i<potezi.size()-1;i++)
        {
            m.getPotezi().add(potezi.get(i));
        }
        m.fireTableDataChanged();
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_start1;
    private javax.swing.JButton jButton_start2;
    private javax.swing.JButton jButton_start3;
    private javax.swing.JButton jButton_start4;
    private javax.swing.JButton jButton_stop1;
    private javax.swing.JButton jButton_stop2;
    private javax.swing.JButton jButton_stop3;
    private javax.swing.JButton jButton_stop4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_namestu;
    private javax.swing.JLabel jLabel_nije;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables


 }
